package com.sailthru.deliverability.api;

public enum BounceRuleType {
    SPAMRELATED, VIRUSRELATED, CONTENTRELATED, QUOTAISSUES, INVALIDSENDER, ROUTINGERRORS, INACTIVEMAILBOX, OTHER, BADMAILBOX, RELAYINGISSUES, BADDOMAIN, POLICYRELATED, PROTOCOLERRORS, SUCCESS, BADCONFIGURATION, NOANSWERFROMHOST, BADCONNECTION, MESSAGEEXPIRED
}
